const mongoose = require("mongoose");
 const orderSchema = new mongoose.Schema(
  { userId: { type: mongoose.Schema.Types.ObjectId, ref: 
      "User", required: true,
    },
    communityId: { type: String, required: false, index: true,
    },
    name: { type: String, required: false, default: "",
    },
    email: { type: String, required: false, default: "",
    },
    phone: { type: String, required: false, default: "",
    },
    service: { type: String, required: true,
    },
    plan: { type: String, required: true,
    },
    price: { type: Number, required: true,
    },
    paymentMethod: { type: String, default: "",
    },
    transactionId: { type: String, default: "",
    },
    playerId: { type: String, default: "",
    },
    profit: { type: Number, default: 0,
    },
    status: { type: String, default: "En attente",
    },
    paymentStatus: { type: String, default: "En attente",
    },
  },
  { timestamps: true,
  }
);
module.exports = mongoose.model("Order", orderSchema);
